INSERT INTO RAW_ORDER
WITH incremental_orders AS (
    SELECT *
    FROM FRESH_ORDERS
    WHERE CAST(ORDERID AS BIGINT) > (SELECT MAX(CAST(ORDERID AS BIGINT)) FROM RAW_ORDER)
)
SELECT * FROM incremental_orders