WITH incremental_orders AS (
    SELECT *
    FROM FRESH_ORDERDETAIL
    WHERE CAST(ORDERID AS BIGINT) > (SELECT MAX(CAST(ORDERID AS BIGINT)) FROM FRESH_ORDERDETAIL)
)

INSERT INTO RAW_ORDERDETAIL
SELECT *
FROM incremental_orders;