WITH incremental_orders AS (
    SELECT *
    FROM FRESH_ORDERS
    WHERE CAST(ORDERID AS BIGINT) > (SELECT MAX(CAST(ORDERID AS BIGINT)) FROM FRESH_ORDERS)
)

INSERT INTO RAW_ORDER
VALUES SELECT *
FROM incremental_orders;